services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
     # - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_PASSWORD: postgrespassword
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      retries: 5
      start_period: 10s
  hasura:
    image: hasura/graphql-engine
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey	
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: >
        {
          "type": "RS256",
          "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
          "issuer": "https://securetoken.google.com/connectable-9bdb7",
          "claims_namespace_path": "$[\"https://hasura.io/jwt/claims\"]"
        }

volumes:
  db_data: null
